version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deploystudy
permissions:
  - object: /home/ubuntu/deploystudy
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 300
      runas: ubuntu